#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define USB_SUSPEND_WAKEUP_DELAY 0
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "YlbxQ/DzneAZ"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define MAX_DEFERRED_EXECUTORS 10